# Gopkg.toml example
#
# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/pborman/uuid"
  version = "1.0.0"

[[constraint]]
  name = "github.com/uber-go/tally"
  version = "3.3.1"

[[constraint]]
  name = "go.uber.org/cadence"
  version = "0.8.8"

[[constraint]]
  name = "go.uber.org/yarpc"
  version = "1.29.1"

[[constraint]]
  name = "go.uber.org/zap"
  version = "1.8.0"

[[override]]
  name = "github.com/apache/thrift"
  #packages = ["lib/go/thrift"]
  revision = "9549b25c77587b29be4e0b5c258221a4ed85d37a"

[prune]
  go-tests = true
  unused-packages = true
